In [1]:
import math
print(math.sqrt(25))
print(math.factorial(5))
print(math.pi)
print(math.e)
print(math.sin(math.radians(30)))

5.0
120
3.141592653589793
2.718281828459045
0.49999999999999994


In [5]:
import math
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [10]:

arr=np.array([[1,2,3,4]])
print(arr)
matrix=np.array([[1,2],[3,4]])
print(matrix)
print(np.zeros((2,3)))
print(np.ones((3,3)))
print(np.arange(0,10,2))

a=np.array([10,20,30])
b=np.array([1,2,3])
print(a*b)
print(a+b)
print(np.mean(arr))
print(np.std(arr))


[[1 2 3 4]]
[[1 2]
 [3 4]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[0 2 4 6 8]
[10 40 90]
[11 22 33]
2.5
1.118033988749895


In [8]:
df=pd.read_csv('Algerian_forest_fires_dataset.csv')

In [9]:
df.head()

day month  year Temperature  RH  Ws Rain   FFMC  DMC    DC  ISI  BUI  FWI  \
0   1     6  2012          29  57  18     0  65.7  3.4   7.6  1.3  3.4  0.5   
1   2     6  2012          29  61  13   1.3  64.4  4.1   7.6    1  3.9  0.4   
2   3     6  2012          26  82  22  13.1  47.1  2.5   7.1  0.3  2.7  0.1   
3   4     6  2012          25  89  13   2.5  28.6  1.3   6.9    0  1.7    0   
4   5     6  2012          27  77  16     0  64.8    3  14.2  1.2  3.9  0.5   

     Classes    
0  not fire     
1  not fire     
2  not fire     
3  not fire     
4  not fire

In [ ]:

data=[10,20,30,40]
series=pd.Series(data)
print(series)

0    10
1    20
2    30
3    40
dtype: int64


In [ ]:
data={'Name':['Alice','Bob','Charlie'],
      'Age':[25,30,35],
      'Salary':[50000,60000,70000]}
df=pd.DataFrame(data)
print
pd.Da


      Name  Age  Salary
0    Alice   25   50000
1      Bob   30   60000
2  Charlie   35   70000
