In [1]:
import math
print(math.sqrt(25))
print(math.factorial(5))
print(math.pi)
print(math.e)
print(math.sin(math.radians(30)))

5.0
120
3.141592653589793
2.718281828459045
0.49999999999999994


In [2]:
import math
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:

arr=np.array([[1,2,3,4]])
print(arr)
matrix=np.array([[1,2],[3,4]])
print(matrix)
print(np.zeros((2,3)))
print(np.ones((3,3)))
print(np.arange(0,10,2))

a=np.array([10,20,30])
b=np.array([1,2,3])
print(a*b)
print(a+b)
print(np.mean(arr))
print(np.std(arr))


[[1 2 3 4]]
[[1 2]
 [3 4]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[0 2 4 6 8]
[10 40 90]
[11 22 33]
2.5
1.118033988749895


In [17]:
df=pd.read_csv('Algerian_forest_fires_dataset.csv')
df.head()
df.isnull()
df.isnull().sum()

day            1
month          2
year           2
Temperature    2
 RH            2
 Ws            2
Rain           2
FFMC           2
DMC            2
DC             2
ISI            2
BUI            2
FWI            2
Classes        3
dtype: int64

In [18]:
print(df.head(3))
print(df.tail(2))
print(df.shape)
print(df.info())
print(df.describe())

  day month  year Temperature  RH  Ws Rain   FFMC  DMC   DC  ISI  BUI  FWI  \
0   1     6  2012          29  57  18     0  65.7  3.4  7.6  1.3  3.4  0.5   
1   2     6  2012          29  61  13   1.3  64.4  4.1  7.6    1  3.9  0.4   
2   3     6  2012          26  82  22  13.1  47.1  2.5  7.1  0.3  2.7  0.1   

     Classes    
0  not fire     
1  not fire     
2  not fire     
    day month  year Temperature  RH  Ws Rain   FFMC  DMC    DC  ISI  BUI  FWI  \
245  29     9  2012          24  54  18   0.1  79.7  4.3  15.2  1.7  5.1  0.7   
246  30     9  2012          24  64  15   0.2  67.3  3.8  16.5  1.2  4.8  0.5   

        Classes    
245   not fire     
246  not fire      
(247, 14)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 247 entries, 0 to 246
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   day          246 non-null    object
 1   month        245 non-null    object
 2   year         245 non-null    ob

In [20]:
print(df['month'])
print(df[['month','year']])

0      6
1      6
2      6
3      6
4      6
      ..
242    9
243    9
244    9
245    9
246    9
Name: month, Length: 247, dtype: object
    month  year
0       6  2012
1       6  2012
2       6  2012
3       6  2012
4       6  2012
..    ...   ...
242     9  2012
243     9  2012
244     9  2012
245     9  2012
246     9  2012

[247 rows x 2 columns]


In [21]:
print(df.iloc[0])

day                      1
month                    6
year                  2012
Temperature             29
 RH                     57
 Ws                     18
Rain                     0
FFMC                  65.7
DMC                    3.4
DC                     7.6
ISI                    1.3
BUI                    3.4
FWI                    0.5
Classes        not fire   
Name: 0, dtype: object


In [22]:
df.describe()

day month  year Temperature   RH   Ws Rain   FFMC  DMC   DC  ISI  BUI  \
count   246   245   245         245  245  245   245   245  245  245  245  245   
unique   33     5     2          20   63   19    40   174  167  199  107  175   
top       1     7  2012          35   64   14     0  88.9  7.9    8  1.1    3   
freq      8    62   244          29   10   43   133     8    5    5    8    5   

        FWI Classes    
count   245       244  
unique  127         9  
top     0.4   fire     
freq     12       131

In [23]:
print(df.loc[1])

day                      2
month                    6
year                  2012
Temperature             29
 RH                     61
 Ws                     13
Rain                   1.3
FFMC                  64.4
DMC                    4.1
DC                     7.6
ISI                      1
BUI                    3.9
FWI                    0.4
Classes        not fire   
Name: 1, dtype: object
